LLVM_CONFIG = llvm-config-18
CXX = clang++-18

CXXFLAGS = `$(LLVM_CONFIG) --cxxflags` \
		 -Iinclude \
           -fPIC \
           -shared \
           -fno-rtti \
           -std=c++17

LDFLAGS = `$(LLVM_CONFIG) --ldflags --system-libs --libs core passes support`

TARGET = libMyPass.so

SRC = $(wildcard src/passes/*.cpp)
IR ?= output.ll

all:
	@echo Building...
	@$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET) $(LDFLAGS)

run:
	@echo Running Passes...
	@opt-18 -load-pass-plugin=./libMyPass.so -passes="alg" $(IR) -S -o opt_output.ll

clean:
	rm -f $(TARGET) output.ll *.o
